language: c

os: linux
compiler: clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
      - OPENSSL="1.0.2"
    - os: linux
      dist: trusty
      sudo: required
      env:
      - OPENSSL="1.1.0"
    - os: osx
      osx_image: xcode8.2
  exclude:
    - compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:george-edison55/cmake-3.x -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$OPENSSL" == "1.0.2" ]]; then sudo add-apt-repository ppa:0k53d-karl-f830m/openssl -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$OPENSSL" == "1.0.2" ]]; then sudo apt-get install openssl -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cmake -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$OPENSSL" == "1.1.0" ]]; then git clone https://github.com/openssl/openssl.git; cd openssl; git checkout tags/OpenSSL_1_1_0e; ./config shared no-threads; make; sudo make install; sudo rm /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcrypto.a; cd ..; fi

script:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -f makefile.linux release; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CI_FLAGS='--ci'; make -f makefile.linux test; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make -f makefile.osx release; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CI_FLAGS='--ci'; make -f makefile.osx test.release; fi
