language: c

os: linux
compiler: clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.2
  exclude:
    - compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:george-edison55/cmake-3.x -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:0k53d-karl-f830m/openssl -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install openssl -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cmake -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install cmake; brew install pkgconfig; fi

script:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -f makefile.linux release; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -f makefile.linux test; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make -f makefile.osx release; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make -f makefile.osx test.release; fi
